# Generated by Django 3.2.12 on 2022-03-24 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivatedInviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Инвайт код')),
            ],
            options={
                'verbose_name': 'Инвайт код',
                'verbose_name_plural': 'Инвайт код',
            },
        ),
        migrations.AddField(
            model_name='referraluser',
            name='activated_invite_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='referral.activatedinvitecode'),
        ),
    ]
