# Generated by Django 3.2.12 on 2022-03-24 07:18

from django.db import migrations
from django_celery_beat.models import PeriodicTask, IntervalSchedule


def create_check_tasks_task(apps, schema_editor):
    """ Создает таску, для проверки не актуальных тасок
        Каждые 2 минуты она будет чистить не используемые таски
    """
    schedule, created = IntervalSchedule.objects.get_or_create(
        every=2,
        period=IntervalSchedule.MINUTES,
    )
    PeriodicTask.objects.create(
        interval=schedule,
        name="Check Tasks",
        task="referral.check_tasks_task",
        enabled=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_auto_20220324_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referraluser',
            name='activated_invite_code',
        ),
        migrations.DeleteModel(
            name='ActivatedInviteCode',
        ),
    ]
