# Generated by Django 3.2.12 on 2022-03-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_auto_20220324_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(verbose_name='Код подтверждения')),
            ],
            options={
                'verbose_name': 'Код подтверждения',
                'verbose_name_plural': 'Код подтверждения',
            },
        ),
    ]
