# Generated by Django 3.2.12 on 2022-03-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0004_smscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscode',
            name='phone',
            field=models.CharField(default=0, max_length=11, unique=True, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
